### ISSUE TITLE
Exec test path not qualified

### ISSUE THREAD

**Issue by Conzar** [vamsee/puppet-solr#21]
In config.pp , lines 45, 54, 63 use an un qualified path for an executable.  See error below:

```
Error: Parameter onlyif failed on Exec[solr-download]: 'test ! -d /usr/share/solr/WEB-INF && test ! -f /tmp/solr-4.9.1.tgz' is not qualified and no path was specified.
```

The fix is to use 
```/usr/bin/test``` instead of ```test```

I could create a fork but I think its easier if you just make the change.  This error renders the class unusable.

**Comment by vamsee** [comment]
That is strange. I'm setting the path (before command) for this very same reason. If wget works, this should work too. Is there anything special about this system you're trying this on?

**Comment by Conzar** [comment]
wget doesn't work.  I just didn't report it.  I ended up creating my own solr class as I needed it to work with both Ubuntu & Centos though.  https://github.com/Conzar/solr
